### ISSUE TITLE
save test images

### ISSUE THREAD

**Issue by amna-mujahid** [wocns1457/GAN-based-face-mask-removal#3]
thank you so much for your hardwork. I want your help as I am unable to save generated test images. I want to calculate FID score but generated test images are not saving.  I used "plt.savefig('image3.png', dpi=300, bbox_inches='tight')" but it is saving the whole plot not single image. please tell me how to save test images.

**Comment by wocns1457** [comment]
Try using
 ```
matplotlib.pyplot.imsave(fname, arr, **kwargs)
 ```
I used the image saving function provided by tensorflow.
